title: "Woozle's Trace"
description: "Notes and articles on software development."

# Visual appearance with no theme looks the best for me
# theme: jekyll-theme-minimalist

permalink: /:path/:basename/
